/* Auto-generated by scripts/extract-boxer-parts.py — do not edit */
export default {
  "sourceSize": [
    1086,
    1448
  ],
  "joints": {
    "head_top": [
      543,
      72
    ],
    "neck": [
      543,
      248
    ],
    "chest": [
      543,
      360
    ],
    "waist": [
      543,
      565
    ],
    "shoulder_l": [
      248,
      318
    ],
    "shoulder_r": [
      838,
      318
    ],
    "elbow_l": [
      148,
      538
    ],
    "elbow_r": [
      938,
      538
    ],
    "wrist_l": [
      108,
      698
    ],
    "wrist_r": [
      978,
      698
    ],
    "hand_l": [
      88,
      792
    ],
    "hand_r": [
      998,
      792
    ],
    "hip_l": [
      418,
      668
    ],
    "hip_r": [
      668,
      668
    ],
    "knee_l": [
      398,
      968
    ],
    "knee_r": [
      688,
      968
    ],
    "ankle_l": [
      368,
      1198
    ],
    "ankle_r": [
      718,
      1198
    ],
    "foot_l": [
      348,
      1378
    ],
    "foot_r": [
      738,
      1378
    ]
  },
  "torsoAttach": {
    "neck": [
      543,
      248
    ],
    "shoulder_l": [
      248,
      318
    ],
    "shoulder_r": [
      838,
      318
    ],
    "waist": [
      543,
      565
    ],
    "hip_l": [
      418,
      668
    ],
    "hip_r": [
      668,
      668
    ]
  },
  "parts": {
    "head": {
      "pivot": [
        0.4986,
        0.8631
      ],
      "attach": [
        0.4986,
        0.1328
      ],
      "width": 355,
      "height": 241,
      "zIndex": 28,
      "src": "/boxer/parts/head.png",
      "aspect": 1.473
    },
    "torso": {
      "pivot": [
        0.4992,
        1.0121
      ],
      "attach": [
        0.4992,
        0.3927
      ],
      "width": 655,
      "height": 331,
      "zIndex": 12,
      "src": "/boxer/parts/torso.png",
      "aspect": 1.9789
    },
    "pelvis": {
      "pivot": [
        0.4989,
        0.2239
      ],
      "attach": [
        0.2242,
        0.7363
      ],
      "width": 455,
      "height": 201,
      "zIndex": 10,
      "src": "/boxer/parts/pelvis.png",
      "aspect": 2.2637
    },
    "upper-arm-left": {
      "pivot": [
        0.5311,
        0.2064
      ],
      "attach": [
        0.1162,
        0.9893
      ],
      "width": 241,
      "height": 281,
      "zIndex": 18,
      "src": "/boxer/parts/upper-arm-left.png",
      "aspect": 0.8577
    },
    "forearm-left": {
      "pivot": [
        0.4887,
        0.2776
      ],
      "attach": [
        0.3077,
        0.847
      ],
      "width": 221,
      "height": 281,
      "zIndex": 20,
      "src": "/boxer/parts/forearm-left.png",
      "aspect": 0.7865
    },
    "glove-left": {
      "pivot": [
        0.4171,
        0.3256
      ],
      "attach": [
        0.3223,
        0.6379
      ],
      "width": 211,
      "height": 301,
      "zIndex": 35,
      "src": "/boxer/parts/glove-left.png",
      "aspect": 0.701
    },
    "upper-arm-right": {
      "pivot": [
        0.4647,
        0.2064
      ],
      "attach": [
        0.8797,
        0.9893
      ],
      "width": 241,
      "height": 281,
      "zIndex": 18,
      "src": "/boxer/parts/upper-arm-right.png",
      "aspect": 0.8577
    },
    "forearm-right": {
      "pivot": [
        0.5068,
        0.2776
      ],
      "attach": [
        0.6878,
        0.847
      ],
      "width": 221,
      "height": 281,
      "zIndex": 20,
      "src": "/boxer/parts/forearm-right.png",
      "aspect": 0.7865
    },
    "glove-right": {
      "pivot": [
        0.5782,
        0.3256
      ],
      "attach": [
        0.673,
        0.6379
      ],
      "width": 211,
      "height": 301,
      "zIndex": 35,
      "src": "/boxer/parts/glove-right.png",
      "aspect": 0.701
    },
    "thigh-left": {
      "pivot": [
        0.5373,
        0.0997
      ],
      "attach": [
        0.4378,
        0.8871
      ],
      "width": 201,
      "height": 381,
      "zIndex": 5,
      "src": "/boxer/parts/thigh-left.png",
      "aspect": 0.5276
    },
    "calf-left": {
      "pivot": [
        0.5373,
        0.1053
      ],
      "attach": [
        0.3881,
        0.7424
      ],
      "width": 201,
      "height": 361,
      "zIndex": 6,
      "src": "/boxer/parts/calf-left.png",
      "aspect": 0.5568
    },
    "boot-left": {
      "pivot": [
        0.4675,
        0.1468
      ],
      "attach": [
        0.381,
        0.7611
      ],
      "width": 231,
      "height": 293,
      "zIndex": 7,
      "src": "/boxer/parts/boot-left.png",
      "aspect": 0.7884
    },
    "thigh-right": {
      "pivot": [
        0.4577,
        0.0997
      ],
      "attach": [
        0.5572,
        0.8871
      ],
      "width": 201,
      "height": 381,
      "zIndex": 5,
      "src": "/boxer/parts/thigh-right.png",
      "aspect": 0.5276
    },
    "calf-right": {
      "pivot": [
        0.4577,
        0.1053
      ],
      "attach": [
        0.607,
        0.7424
      ],
      "width": 201,
      "height": 361,
      "zIndex": 6,
      "src": "/boxer/parts/calf-right.png",
      "aspect": 0.5568
    },
    "boot-right": {
      "pivot": [
        0.5281,
        0.1468
      ],
      "attach": [
        0.6147,
        0.7611
      ],
      "width": 231,
      "height": 293,
      "zIndex": 7,
      "src": "/boxer/parts/boot-right.png",
      "aspect": 0.7884
    }
  },
  "scaleVmin": 36,
  "torsoAttachNorm": {
    "neck": [
      0.4992,
      0.0544
    ],
    "shoulder_l": [
      0.0489,
      0.2659
    ],
    "shoulder_r": [
      0.9496,
      0.2659
    ],
    "waist": [
      0.4992,
      1.0121
    ],
    "hip_l": [
      0.3084,
      1.3233
    ],
    "hip_r": [
      0.6901,
      1.3233
    ]
  },
  "pelvisAttachNorm": {
    "hip_l": [
      0.2242,
      0.7363
    ],
    "hip_r": [
      0.7736,
      0.7363
    ]
  }
} as const;
