/* Auto-generated by scripts/map-face-template.py — do not edit */
export default {
  "template": "/faces/test-template-face.png",
  "sourceSize": [
    1024,
    1024
  ],
  "faceOval": [
    0.1748,
    0.0352,
    0.8682,
    0.8252
  ],
  "regions": {
    "leftEye": [
      0.2996,
      0.2564,
      0.4521,
      0.3512
    ],
    "rightEye": [
      0.5908,
      0.2564,
      0.7434,
      0.3512
    ],
    "nose": [
      0.4244,
      0.3512,
      0.6186,
      0.4776
    ],
    "mouth": [
      0.3689,
      0.4934,
      0.674,
      0.6198
    ]
  },
  "landmarks": {
    "leftEye": [
      0.3759,
      0.3038
    ],
    "rightEye": [
      0.6671,
      0.3038
    ],
    "nose": [
      0.5215,
      0.4144
    ],
    "mouth": [
      0.5215,
      0.5566
    ],
    "chin": [
      0.5215,
      0.8252
    ]
  },
  "targets": {
    "heavyBag": {
      "comment": "Screen trapezoid \u2014 matches BAG_HIT_CORNERS in gloveZoneGrid.ts",
      "corners": [
        [
          0.305,
          0.18
        ],
        [
          0.685,
          0.18
        ],
        [
          0.695,
          0.46
        ],
        [
          0.295,
          0.46
        ]
      ]
    },
    "heavyBagMesh": {
      "comment": "3D decal on cylinder body (bag-local metres)",
      "center": [
        0,
        0.35,
        0.44
      ],
      "size": [
        0.52,
        0.62
      ]
    },
    "ringPartner": {
      "comment": "Square head slot on sparring-boxer silhouette (1024\u00d71536 norm)",
      "rect": [
        0.4269,
        0.1143,
        0.5731,
        0.2118
      ]
    },
    "hudPlayer": {
      "rect": [
        0.02,
        0.02,
        0.22,
        0.18
      ]
    },
    "hudOpponent": {
      "rect": [
        0.78,
        0.02,
        0.98,
        0.18
      ]
    }
  }
} as const;
